name: Run Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup venv and pip
      run: |
        python3 -m ensurepip
        pip -V
        python3 -m pip -V
        python3 -m venv venv

    - name: Setup environment (Unix)
      if: runner.os != 'Windows'
      run: source venv/bin/activate

    - name: Setup environment (Windows)
      if: runner.os == 'Windows'
      run: .\\venv\\Scripts\\activate.bat

    - name: Install the package
      run: pip install -e ".[testing]"

    - name: Run pytest
      run: pytest tests -vvv

    - name: Run mypy
      run: mypy src/isisdl/backend/crud.py src/isisdl/backend/models.py src/isisdl/api src/isisdl/db_conf.py src/isisdl/__main__.py src/isisdl/settings.py src/isisdl/utils.py tests

    - name: Run flake8
      run: flake8 src/isisdl/backend/crud.py src/isisdl/backend/models.py src/isisdl/api src/isisdl/db_conf.py src/isisdl/__main__.py src/isisdl/settings.py src/isisdl/utils.py tests
